package com.swisssigner.service;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Service
public class AnalysisConfirmationPdfService {

    public byte[] createConfirmation(String analysisProcessId,
                                     String status,
                                     String statusUrl,
                                     String language,
                                     Map<String, Object> analysisResult) throws IOException {
        Locale locale = resolveLocale(language);
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            float margin = 52f;
            float width = page.getMediaBox().getWidth();
            float y;

            try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                y = JustSignPdfTemplateSupport.drawHeader(document, page, content, margin);
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    autoGeneratedLabel(locale),
                    PDType1Font.HELVETICA,
                    9.5f,
                    width,
                    y,
                    JustSignPdfTemplateSupport.MUTED_R,
                    JustSignPdfTemplateSupport.MUTED_G,
                    JustSignPdfTemplateSupport.MUTED_B
                );
                y -= 22f;

                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    title(locale),
                    PDType1Font.HELVETICA_BOLD,
                    18f,
                    width,
                    y,
                    JustSignPdfTemplateSupport.PRIMARY_R,
                    JustSignPdfTemplateSupport.PRIMARY_G,
                    JustSignPdfTemplateSupport.PRIMARY_B
                );
                y -= 14f;

                y = writeSectionTitle(content, processIdTitle(locale), width, y);
                y -= 10f;
                y = JustSignPdfTemplateSupport.drawCenteredInfoBox(content, analysisProcessId, width, y, 430f, 30f);
                y -= 12f;

                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    statusLabel(locale) + status,
                    PDType1Font.HELVETICA_BOLD,
                    10f,
                    width,
                    y,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 11f;
                String generated = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'")
                    .withZone(ZoneOffset.UTC)
                    .format(Instant.now());
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    createdLabel(locale) + generated,
                    PDType1Font.HELVETICA,
                    9.5f,
                    width,
                    y,
                    JustSignPdfTemplateSupport.MUTED_R,
                    JustSignPdfTemplateSupport.MUTED_G,
                    JustSignPdfTemplateSupport.MUTED_B
                );
                y -= 12f;

                if (analysisResult != null && !analysisResult.isEmpty()) {
                    y = writeSectionTitle(content, resultTitle(locale), width, y);
                    y -= 10f;
                    y = JustSignPdfTemplateSupport.writeWrapped(
                        content,
                        summaryLine(locale) + safeSummary(analysisResult),
                        PDType1Font.HELVETICA,
                        9.2f,
                        margin,
                        y,
                        width - (2 * margin),
                        JustSignPdfTemplateSupport.BODY_R,
                        JustSignPdfTemplateSupport.BODY_G,
                        JustSignPdfTemplateSupport.BODY_B
                    );
                    y -= 4f;
                    y = JustSignPdfTemplateSupport.write(
                        content,
                        confidenceLine(locale) + safeConfidence(analysisResult) + " | " + consensusLine(locale) + safeConsensus(analysisResult),
                        PDType1Font.HELVETICA_BOLD,
                        9.2f,
                        margin,
                        y,
                        JustSignPdfTemplateSupport.MUTED_R,
                        JustSignPdfTemplateSupport.MUTED_G,
                        JustSignPdfTemplateSupport.MUTED_B
                    );
                    y -= 10f;
                    y = JustSignPdfTemplateSupport.write(
                        content,
                        keyDatesTitle(locale),
                        PDType1Font.HELVETICA_BOLD,
                        9.8f,
                        margin,
                        y,
                        JustSignPdfTemplateSupport.PRIMARY_R,
                        JustSignPdfTemplateSupport.PRIMARY_G,
                        JustSignPdfTemplateSupport.PRIMARY_B
                    );
                    y -= 10f;
                    y = JustSignPdfTemplateSupport.writeWrapped(
                        content,
                        listText(safeList(analysisResult, "key_dates"), "date", "label"),
                        PDType1Font.HELVETICA,
                        9.2f,
                        margin,
                        y,
                        width - (2 * margin),
                        JustSignPdfTemplateSupport.BODY_R,
                        JustSignPdfTemplateSupport.BODY_G,
                        JustSignPdfTemplateSupport.BODY_B
                    );
                    y -= 8f;
                    y = JustSignPdfTemplateSupport.write(
                        content,
                        risksTitle(locale),
                        PDType1Font.HELVETICA_BOLD,
                        9.8f,
                        margin,
                        y,
                        JustSignPdfTemplateSupport.PRIMARY_R,
                        JustSignPdfTemplateSupport.PRIMARY_G,
                        JustSignPdfTemplateSupport.PRIMARY_B
                    );
                    y -= 10f;
                    y = JustSignPdfTemplateSupport.writeWrapped(
                        content,
                        listText(safeList(analysisResult, "risks"), "risk", "title"),
                        PDType1Font.HELVETICA,
                        9.2f,
                        margin,
                        y,
                        width - (2 * margin),
                        JustSignPdfTemplateSupport.BODY_R,
                        JustSignPdfTemplateSupport.BODY_G,
                        JustSignPdfTemplateSupport.BODY_B
                    );
                    y -= 10f;
                }

                y = writeSectionTitle(content, usageTitle(locale), width, y);
                y -= 10f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    usageBody(locale),
                    PDType1Font.HELVETICA,
                    10f,
                    width,
                    y,
                    width - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 8f;
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    statusUrlLabel(locale),
                    PDType1Font.HELVETICA_BOLD,
                    10f,
                    width,
                    y,
                    JustSignPdfTemplateSupport.PRIMARY_R,
                    JustSignPdfTemplateSupport.PRIMARY_G,
                    JustSignPdfTemplateSupport.PRIMARY_B
                );
                y -= 11f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    statusUrl,
                    PDType1Font.COURIER,
                    9f,
                    width,
                    y,
                    width - 120f,
                    24,
                    94,
                    180
                );
                y -= 10f;
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        }
    }

    private float writeSectionTitle(PDPageContentStream content, String title, float pageWidth, float y) throws IOException {
        return JustSignPdfTemplateSupport.writeCentered(
            content,
            title,
            PDType1Font.HELVETICA_BOLD,
            12.8f,
            pageWidth,
            y,
            JustSignPdfTemplateSupport.PRIMARY_R,
            JustSignPdfTemplateSupport.PRIMARY_G,
            JustSignPdfTemplateSupport.PRIMARY_B
        );
    }

    private String autoGeneratedLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Cette confirmation a ete generee automatiquement.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "This confirmation was generated automatically.";
        }
        return "Diese Bestaetigung wurde automatisch erstellt.";
    }

    private String title(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Analyse IA erfolgreich gestartet";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "AI analysis started successfully";
        return "AI-Analyse erfolgreich gestartet";
    }

    private String processIdTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "1) analyticProcessID";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "1) analyticProcessID";
        return "1) analyticProcessID";
    }

    private String statusLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Statut: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Status: ";
        return "Status: ";
    }

    private String createdLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Cree le: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Created at: ";
        return "Erstellt am: ";
    }

    private String usageTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Utilisation de l analyticProcessID";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "How to use analyticProcessID";
        return "So verwenden Sie die analyticProcessID";
    }

    private String usageBody(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Saisissez cet analyticProcessID dans le status checker justSign pour recuperer l avancement et les resultats de l analyse.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "Enter this analyticProcessID in the justSign status checker to retrieve analysis progress and results.";
        }
        return "Geben Sie diese analyticProcessID im justSign Status Checker ein, um Fortschritt und Ergebnisse der Analyse abzurufen.";
    }

    private String statusUrlLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "URL status checker:";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Status checker URL:";
        return "Status-Checker-URL:";
    }

    private String resultTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Resultat actuel";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Current result snapshot";
        return "Aktueller Ergebnisstand";
    }

    private String summaryLine(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Resume: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Summary: ";
        return "Zusammenfassung: ";
    }

    private String confidenceLine(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Confiance: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Confidence: ";
        return "Confidence: ";
    }

    private String consensusLine(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Consensus: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Consensus: ";
        return "Konsens: ";
    }

    private String keyDatesTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Dates importantes";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Key dates";
        return "Wichtige Daten";
    }

    private String risksTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Principaux risques";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Top risks";
        return "Top Risiken";
    }

    private String safeSummary(Map<String, Object> analysisResult) {
        Object summary = analysisResult.get("summary");
        if (summary instanceof String s && !s.isBlank()) return s;
        if (summary instanceof Map<?, ?> map) {
            Object executive = map.get("executive");
            if (executive instanceof String s && !s.isBlank()) return s;
            Object plain = map.get("plain_language");
            if (plain instanceof String s && !s.isBlank()) return s;
        }
        Object executiveSummary = analysisResult.get("executive_summary");
        if (executiveSummary instanceof String s && !s.isBlank()) return s;
        return "n/a";
    }

    @SuppressWarnings("unchecked")
    private String safeConfidence(Map<String, Object> analysisResult) {
        Object confidence = analysisResult.get("confidence");
        if (confidence instanceof Number n) {
            return String.valueOf(n.intValue()) + "/100";
        }
        if (confidence instanceof Map<?, ?> map) {
            Object score = map.get("overall_score");
            if (score == null) score = map.get("score");
            if (score != null) return String.valueOf(score) + "/100";
        }
        return "n/a";
    }

    @SuppressWarnings("unchecked")
    private String safeConsensus(Map<String, Object> analysisResult) {
        Object consensus = analysisResult.get("consensus");
        if (consensus instanceof Map<?, ?> map) {
            Object agreement = map.get("critical_claims_agreement");
            if (agreement instanceof Number n) {
                double pct = n.doubleValue() <= 1.0 ? n.doubleValue() * 100.0 : n.doubleValue();
                return String.format(Locale.ROOT, "%.0f%%", pct);
            }
            if (agreement != null) {
                return String.valueOf(agreement);
            }
        }
        return "n/a";
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> safeList(Map<String, Object> analysisResult, String key) {
        Object value = analysisResult.get(key);
        if (!(value instanceof List<?>)) {
            if ("risks".equals(key)) {
                value = analysisResult.get("top_risks");
            } else if ("opportunities".equals(key)) {
                value = analysisResult.get("top_opportunities");
            }
        }
        if (value instanceof List<?> list) {
            List<Map<String, Object>> out = new ArrayList<>();
            for (Object item : list) {
                if (item instanceof Map<?, ?> map) {
                    out.add((Map<String, Object>) map);
                }
                if (out.size() >= 5) break;
            }
            return out;
        }
        return List.of();
    }

    private String listText(List<Map<String, Object>> list, String firstKey, String secondKey) {
        if (list.isEmpty()) return "- n/a";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < list.size(); i++) {
            Map<String, Object> item = list.get(i);
            Object first = item.get(firstKey);
            Object second = item.get(secondKey);
            String firstStr = first == null ? "n/a" : String.valueOf(first);
            String secondStr = second == null ? "" : String.valueOf(second);
            sb.append(i + 1).append(") ").append(firstStr);
            if (!secondStr.isBlank() && !secondStr.equals("n/a")) {
                sb.append(" - ").append(secondStr);
            }
            if (i < list.size() - 1) sb.append("\n");
        }
        return sb.toString();
    }

    private Locale resolveLocale(String language) {
        if (language == null || language.isBlank()) return Locale.GERMAN;
        String normalized = language.toLowerCase(Locale.ROOT);
        if (normalized.startsWith("fr")) return Locale.FRENCH;
        if (normalized.startsWith("en")) return Locale.ENGLISH;
        return Locale.GERMAN;
    }
}
