package com.swisssigner.service;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Service
public class ConfirmationPdfService {

    public byte[] createProcessStartConfirmation(String processId,
                                                 String statusUrl,
                                                 String language,
                                                 Map<String, Object> analysisResult) throws IOException {
        Locale locale = resolveLocale(language);
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            float margin = 52f;
            float pageWidth = page.getMediaBox().getWidth();
            float y;

            try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                y = JustSignPdfTemplateSupport.drawHeader(document, page, content, margin);
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    autoGeneratedLabel(locale),
                    PDType1Font.HELVETICA,
                    9.5f,
                    pageWidth,
                    y,
                    JustSignPdfTemplateSupport.MUTED_R,
                    JustSignPdfTemplateSupport.MUTED_G,
                    JustSignPdfTemplateSupport.MUTED_B
                );
                y -= 22f;

                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    title(locale),
                    PDType1Font.HELVETICA_BOLD,
                    19f,
                    pageWidth,
                    y,
                    JustSignPdfTemplateSupport.PRIMARY_R,
                    JustSignPdfTemplateSupport.PRIMARY_G,
                    JustSignPdfTemplateSupport.PRIMARY_B
                );
                y -= 14f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    subtitle(locale),
                    PDType1Font.HELVETICA,
                    10.5f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 12f;

                y = writeSectionTitle(content, sectionDoneTitle(locale), pageWidth, y);
                y -= 12f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    sectionDoneBody(locale),
                    PDType1Font.HELVETICA,
                    10f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 10f;

                y = writeSectionTitle(content, sectionNextTitle(locale), pageWidth, y);
                y -= 12f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    sectionNextBody(locale),
                    PDType1Font.HELVETICA,
                    10f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 12f;

                y = writeSectionTitle(content, sectionProcessIdTitle(locale), pageWidth, y);
                y -= 10f;
                y = JustSignPdfTemplateSupport.drawCenteredInfoBox(content, processId, pageWidth, y, 430f, 30f);
                y -= 14f;

                y = writeSectionTitle(content, sectionUseIdTitle(locale), pageWidth, y);
                y -= 12f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    sectionUseIdBody(locale),
                    PDType1Font.HELVETICA,
                    10f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
                y -= 8f;
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    statusLabel(locale),
                    PDType1Font.HELVETICA_BOLD,
                    10f,
                    pageWidth,
                    y,
                    JustSignPdfTemplateSupport.PRIMARY_R,
                    JustSignPdfTemplateSupport.PRIMARY_G,
                    JustSignPdfTemplateSupport.PRIMARY_B
                );
                y -= 12f;
                y = JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    statusUrl,
                    PDType1Font.COURIER,
                    9f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    24,
                    94,
                    180
                );
                y -= 8f;
                String createdAt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'")
                    .withZone(ZoneOffset.UTC)
                    .format(Instant.now());
                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    createdAtLabel(locale) + createdAt,
                    PDType1Font.HELVETICA,
                    9.5f,
                    pageWidth,
                    y,
                    JustSignPdfTemplateSupport.MUTED_R,
                    JustSignPdfTemplateSupport.MUTED_G,
                    JustSignPdfTemplateSupport.MUTED_B
                );
                y -= 12f;

                if (analysisResult != null && !analysisResult.isEmpty()) {
                    y = writeSectionTitle(content, sectionAnalysisTitle(locale), pageWidth, y);
                    y -= 10f;
                    y = JustSignPdfTemplateSupport.writeWrappedCentered(
                        content,
                        analysisSummary(locale, analysisResult),
                        PDType1Font.HELVETICA,
                        9.5f,
                        pageWidth,
                        y,
                        pageWidth - 120f,
                        JustSignPdfTemplateSupport.BODY_R,
                        JustSignPdfTemplateSupport.BODY_G,
                        JustSignPdfTemplateSupport.BODY_B
                    );
                    y -= 10f;
                }

                y = JustSignPdfTemplateSupport.writeCentered(
                    content,
                    sectionSupportTitle(locale, analysisResult != null && !analysisResult.isEmpty()),
                    PDType1Font.HELVETICA_BOLD,
                    13f,
                    pageWidth,
                    y,
                    JustSignPdfTemplateSupport.PRIMARY_R,
                    JustSignPdfTemplateSupport.PRIMARY_G,
                    JustSignPdfTemplateSupport.PRIMARY_B
                );
                y -= 11f;
                JustSignPdfTemplateSupport.writeWrappedCentered(
                    content,
                    sectionSupportBody(locale),
                    PDType1Font.HELVETICA,
                    9.2f,
                    pageWidth,
                    y,
                    pageWidth - 120f,
                    JustSignPdfTemplateSupport.BODY_R,
                    JustSignPdfTemplateSupport.BODY_G,
                    JustSignPdfTemplateSupport.BODY_B
                );
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        }
    }

    private float writeSectionTitle(PDPageContentStream content, String title, float pageWidth, float y) throws IOException {
        return JustSignPdfTemplateSupport.writeCentered(
            content,
            title,
            PDType1Font.HELVETICA_BOLD,
            13f,
            pageWidth,
            y,
            JustSignPdfTemplateSupport.PRIMARY_R,
            JustSignPdfTemplateSupport.PRIMARY_G,
            JustSignPdfTemplateSupport.PRIMARY_B
        );
    }

    private Locale resolveLocale(String language) {
        if (language == null || language.isBlank()) {
            return Locale.GERMAN;
        }
        String normalized = language.trim().toLowerCase(Locale.ROOT);
        if (normalized.startsWith("fr")) return Locale.FRENCH;
        if (normalized.startsWith("en")) return Locale.ENGLISH;
        return Locale.GERMAN;
    }

    private String autoGeneratedLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Cet e-mail a ete genere automatiquement. Merci de ne pas repondre.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "This message was generated automatically. Please do not reply.";
        }
        return "Diese Nachricht wurde automatisch erstellt. Bitte nicht antworten.";
    }

    private String title(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Vous avez demarre le processus de signature avec succes.";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "You have successfully started the signing process.";
        return "Sie haben den Signaturprozess erfolgreich gestartet.";
    }

    private String subtitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Ce document confirme le lancement de votre processus de signature numerique.";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "This document confirms the start of your digital signing process.";
        return "Dieses Dokument bestaetigt den Start Ihres digitalen Signaturprozesses.";
    }

    private String sectionDoneTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "1) Ce qui a ete fait";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "1) What has been done";
        return "1) Was Sie gemacht haben";
    }

    private String sectionDoneBody(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Votre document a ete prepare et le processus de signature a ete declenche.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "Your document was prepared and the signing workflow was started.";
        }
        return "Ihr Dokument wurde vorbereitet und der Signaturablauf wurde gestartet.";
    }

    private String sectionNextTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "2) Comment le processus continue";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "2) How the process continues";
        return "2) Wie es weitergeht";
    }

    private String sectionNextBody(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "1) Les signataires recoivent leur invitation.\n"
                + "2) Ils signent le document.\n"
                + "3) Quand le statut est COMPLETED, tous les signataires ont recu une copie signee.\n"
                + "Pour l archivage, demandez le transfert du document signe.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "1) Signers receive their invitations.\n"
                + "2) They sign the document.\n"
                + "3) When status is COMPLETED, all signers have received a signed copy.\n"
                + "If you need archiving, ask for the signed document to be forwarded.";
        }
        return "1) Unterzeichner erhalten ihre Einladungen.\n"
            + "2) Sie signieren das Dokument.\n"
            + "3) Wenn der Status COMPLETED ist, haben alle Unterzeichner eine unterschriebene Kopie erhalten.\n"
            + "Fuer die Archivierung lassen Sie sich das signierte Dokument weiterleiten.";
    }

    private String sectionProcessIdTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "3) Process ID";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "3) Process ID";
        return "3) Process-ID";
    }

    private String sectionUseIdTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "4) Comment utiliser le Process ID";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "4) How to use the Process ID";
        return "4) So verwenden Sie die Process-ID";
    }

    private String sectionUseIdBody(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Utilisez ce Process ID dans le status checker justSign pour consulter l avancement. Indiquez toujours ce Process ID en cas de question au support.";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "Use this Process ID in the justSign status checker to view progress. Include this Process ID in every support request.";
        }
        return "Nutzen Sie diese Process-ID im justSign Status Checker, um den Fortschritt zu sehen. Geben Sie diese Process-ID bei jeder Support-Anfrage an.";
    }

    private String statusLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Status checker URL:";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Status checker URL:";
        return "Status-Checker-URL:";
    }

    private String createdAtLabel(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "Cree le: ";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "Created at: ";
        return "Erstellt am: ";
    }

    private String sectionSupportTitle(Locale locale, boolean withAnalysisSection) {
        String prefix = withAnalysisSection ? "6) " : "5) ";
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return prefix + "Support Swisscom Sign";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return prefix + "Swisscom Sign support options";
        return prefix + "Swisscom Sign Support-Moeglichkeiten";
    }

    private String sectionSupportBody(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "1) Support & Services (formulaire de support): https://trustservices.swisscom.com/en/support\n"
                + "2) Help Center (Signing Service): https://trustservices.swisscom.com/en/support/help-center/signing-service\n"
                + "3) Service Status: https://trustservices.swisscom.com/en/support/developer-section/service-status?hsLang=en\n"
                + "4) Developer Hub (API): https://dev.trustservices.swisscom.com/";
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "1) Support & Services (support form): https://trustservices.swisscom.com/en/support\n"
                + "2) Help Center (Signing Service): https://trustservices.swisscom.com/en/support/help-center/signing-service\n"
                + "3) Service Status: https://trustservices.swisscom.com/en/support/developer-section/service-status?hsLang=en\n"
                + "4) Developer Hub (API): https://dev.trustservices.swisscom.com/";
        }
        return "1) Support & Services (Support-Formular): https://trustservices.swisscom.com/de/support\n"
            + "2) Help Center (Signing Service): https://trustservices.swisscom.com/de/support/help-center/signing-service\n"
            + "3) Service-Status: https://trustservices.swisscom.com/de/support/developer-section/service-status?hsLang=de\n"
            + "4) Developer Hub (API): https://dev.trustservices.swisscom.com/";
    }

    private String sectionAnalysisTitle(Locale locale) {
        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) return "5) Resultat de l analyse IA (CHF 1.00)";
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) return "5) AI analysis result (CHF 1.00)";
        return "5) KI-Analyse-Ergebnis (CHF 1.00)";
    }

    @SuppressWarnings("unchecked")
    private String analysisSummary(Locale locale, Map<String, Object> analysisResult) {
        String summary = extractAnalysisSummary(analysisResult);
        String confidence = extractConfidence(analysisResult);
        String keyDate = extractTopKeyDate(analysisResult);
        String topRisk = extractTopRisk(analysisResult);

        if (Locale.FRENCH.getLanguage().equals(locale.getLanguage())) {
            return "Contenu: resume, dates importantes, obligations, risques, opportunites et score de confiance.\n"
                + "Resume: " + crop(summary, 260) + "\n"
                + "Confiance: " + confidence + "\n"
                + "Date importante: " + keyDate + "\n"
                + "Risque principal: " + crop(topRisk, 150);
        }
        if (Locale.ENGLISH.getLanguage().equals(locale.getLanguage())) {
            return "Included: summary, key dates, obligations, risks, opportunities, and confidence scoring.\n"
                + "Summary: " + crop(summary, 260) + "\n"
                + "Confidence: " + confidence + "\n"
                + "Key date: " + keyDate + "\n"
                + "Top risk: " + crop(topRisk, 150);
        }
        return "Enthalten: Zusammenfassung, wichtige Daten, Pflichten, Risiken, Chancen und Confidence-Score.\n"
            + "Zusammenfassung: " + crop(summary, 260) + "\n"
            + "Confidence: " + confidence + "\n"
            + "Wichtiges Datum: " + keyDate + "\n"
            + "Top-Risiko: " + crop(topRisk, 150);
    }

    @SuppressWarnings("unchecked")
    private String extractAnalysisSummary(Map<String, Object> analysisResult) {
        Object summary = analysisResult.get("summary");
        if (summary instanceof String s && !s.isBlank()) {
            return s.trim();
        }
        if (summary instanceof Map<?, ?> map) {
            Object exec = map.get("executive");
            if (exec instanceof String s && !s.isBlank()) {
                return s.trim();
            }
        }
        return "No summary available.";
    }

    @SuppressWarnings("unchecked")
    private String extractConfidence(Map<String, Object> analysisResult) {
        Object confidence = analysisResult.get("confidence");
        if (confidence instanceof Map<?, ?> map) {
            Object score = map.get("overall_score");
            if (score == null) {
                score = map.get("score");
            }
            if (score != null) {
                return String.valueOf(score) + "/100";
            }
        }
        return "n/a";
    }

    @SuppressWarnings("unchecked")
    private String extractTopKeyDate(Map<String, Object> analysisResult) {
        Object keyDates = analysisResult.get("key_dates");
        if (keyDates instanceof List<?> list && !list.isEmpty() && list.getFirst() instanceof Map<?, ?> first) {
            String date = first.get("date") == null ? "" : String.valueOf(first.get("date"));
            String label = first.get("label") == null ? "" : String.valueOf(first.get("label"));
            String combined = (date + " " + label).trim();
            if (!combined.isBlank()) {
                return combined;
            }
        }
        return "n/a";
    }

    @SuppressWarnings("unchecked")
    private String extractTopRisk(Map<String, Object> analysisResult) {
        Object risks = analysisResult.get("risks");
        if (risks instanceof List<?> list && !list.isEmpty() && list.getFirst() instanceof Map<?, ?> first) {
            Object risk = first.get("risk");
            if (risk == null) {
                risk = first.get("title");
            }
            if (risk != null) {
                return String.valueOf(risk);
            }
        }
        return "n/a";
    }

    private String crop(String value, int maxLen) {
        if (value == null || value.isBlank()) {
            return "n/a";
        }
        String normalized = value.replaceAll("\\s+", " ").trim();
        if (normalized.length() <= maxLen) {
            return normalized;
        }
        return normalized.substring(0, maxLen - 3) + "...";
    }
}
